#!/usr/bin/env python3
# /// script
# dependencies = [
#   "yfinance",
#   "rich",
#   "pandas",
#   "plotille",
#   "matplotlib",
#   "mplfinance"
# ]
# ///

import runpy
import sys
from pathlib import Path

script = Path(__file__).with_name('yf.py')
sys.argv[0] = str(script)
runpy.run_path(str(script), run_name='__main__')
